[package]
name = "kascov"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
secp256k1 = { version = "0.29.1", features = ["global-context"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dotenvy = "0.15"
walkdir = "2.5"
getrandom = "0.3"
rustyline = "14"
kaspa-grpc-client = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "059d61ec093d2696232d12e4375ec33e21f896f6" }
kaspa-rpc-core = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "059d61ec093d2696232d12e4375ec33e21f896f6" }
kaspa-consensus-core = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "059d61ec093d2696232d12e4375ec33e21f896f6" }
kaspa-addresses = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "059d61ec093d2696232d12e4375ec33e21f896f6" }
kaspa-txscript = { git = "https://github.com/kaspanet/rusty-kaspa", rev = "059d61ec093d2696232d12e4375ec33e21f896f6" }
silverscript-lang = { git = "https://github.com/kaspanet/silverscript.git", rev = "140bf184fd03dc0f5c29155f89e9e5d733a1152f", package = "silverscript-lang" }
argent = { git = "https://github.com/argent-lang/argent.git", rev = "01f4aed1fbe52034b9c55cdfca5a192fba35466b", package = "argent" }
