name: Rust check

on:
  pull_request:

permissions:
  contents: read

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install --yes protobuf-compiler
      - run: cargo check --locked
